{{- if and .Values.secretEnv.enabled .Values.secretEnv.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-deployment.fullname" . }}-env
  labels:
    {{- include "model-deployment.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretEnv.data | nindent 2 }}
{{- end }}
